### ISSUE TITLE
python error

### ISSUE THREAD

**Issue by hgomez** [unilock/makerom-linux#3]
I tried this on an Ubuntu 24.04 (Python 3.12.3, openjdk version "17.0.11") and used this MSI Card as a test

* https://www.techpowerup.com/vgabios/168873/msi-r9280x-3072-140302

I download this ROM so

* https://www.techpowerup.com/vgabios/168873/MSI.R9280X.3072.140302.rom

I used this command line 

```
./makerom.sh  --rom=MSI.R9280X.3072.140302.rom  --deviceid=6798 
```

But 

```
[!] Copying Mac EFI code + ROM header + VBIOS dump to temporary directory...
[!] Patching EFI code + ROM header with appropriate device ID...
Patching files /tmp/tmp.au3dgj7C1K/mac.efi, /tmp/tmp.au3dgj7C1K/header.rom for device-id 0x6798
Successfully patched efi file
Successfully patched efi rom file
[!] Compressing patched EFI code...
[!] Concatenating compressed EFI code to ROM header...
47591+0 enregistrements lus
47591+0 enregistrements écrits
47591 octets (48 kB, 46 KiB) copiés, 0,0205832 s, 2,3 MB/s
[!] Patched EFI is ready!
[!] Concatenating patched EFI to VBIOS dump...
65536+0 enregistrements lus
65536+0 enregistrements écrits
65536 octets (66 kB, 64 KiB) copiés, 0,0273487 s, 2,4 MB/s
[!] Finalizing patched VBIOS...
Before:
OpRom (size=65536, indicator_offset=0x245, indicator=0x0, checksum=0x0)
OpRom (size=48128, indicator_offset=0x31, indicator=0x80, checksum=0x0)
RawData (size=17408)

After:
OpRom (size=65536, indicator_offset=0x245, indicator=0x0, checksum=0x100)
OpRom (size=48128, indicator_offset=0x31, indicator=0x80, checksum=0x1c)
RawData (size=17408)
Traceback (most recent call last):
  File "/home/henri/Téléchargements/makerom-linux/Prgm/fixrom3.py", line 117, in <module>
    f.write(op_rom.dump())
            ^^^^^^^^^^^^^
  File "/home/henri/Téléchargements/makerom-linux/Prgm/fixrom3.py", line 72, in dump
    return bytearray(self.data) + self.next_rom.dump()
           ^^^^^^^^^^^^^^^^^^^^
ValueError: byte must be in range(0, 256)
[!] Cleaning up...
[!] Done! Your patched VBIOS is ready at MSI.R9280X.3072.140302.rom.mac!
```

No mac rom produced ;(

```
-rw-rw-r-- 1 henri henri 131072 sept.  5 17:20 MSI.R9280X.3072.140302.rom
-rw-rw-r-- 1 henri henri      0 sept.  5 17:24 MSI.R9280X.3072.140302.rom.mac
```

Any idea what could go wrong ?

**Comment by hgomez** [comment]
It worked with this model

* https://www.techpowerup.com/vgabios/146769/msi-r9280x-3072-131009
* https://www.techpowerup.com/vgabios/146769/MSI.R9280X.3072.131009.rom

64K file here and 128K file out

```
 64 -rw-rw-r-- 1 henri henri  65536 sept.  5 17:35 MSI.R9280X.3072.131009.rom
128 -rw-rw-r-- 1 henri henri 131072 sept.  5 17:35 MSI.R9280X.3072.131009.rom.mac
```

**Comment by hgomez** [comment]
More on this

It works on most ROMs

* MSI.R9280X.3072.130912.rom
* MSI.R9280X.3072.131009.rom
* MSI.R9280X.3072.131011.rom
* MSI.R9280X.3072.131028.rom
* MSI.R9280X.3072.131029_1.rom
* MSI.R9280X.3072.131029.rom
* MSI.R9280X.3072.131205_1.rom
* MSI.R9280X.3072.131205.rom

But failed on 

* MSI.R9280X.3072.131204.rom
* MSI.R9280X.3072.131226.rom
* MSI.R9280X.3072.140302.rom
* MSI.R9280X.6144.140211.rom
